spring.application.name=mangahub

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/mangahub
spring.datasource.username=postgres
spring.datasource.password=1203

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

app.jwt.secret=${JWT_SECRET:change-this-to-a-real-secret-at-least-256-bits-long-for-hs256}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Flyway Maven Plugin
flyway.url=jdbc:postgresql://localhost:5432/mangahub
flyway.user=postgres
flyway.password=1203

# Hibernate Batch Fetching
spring.jpa.properties.hibernate.default_batch_fetch_size=100